//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teatsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNews
    {
        public tNews()
        {
            this.tComment = new HashSet<tComment>();
        }
    
        public int news_id { get; set; }
        public Nullable<int> subs_id { get; set; }
        public Nullable<int> menus_ids { get; set; }
        public string title { get; set; }
        public string title_more { get; set; }
        public string detials { get; set; }
        public string images { get; set; }
        public Nullable<System.DateTime> addedtime { get; set; }
        public Nullable<int> news_count { get; set; }
        public string news_video { get; set; }
        public string news_audio { get; set; }
    
        public virtual ICollection<tComment> tComment { get; set; }
        public virtual tMenu tMenu { get; set; }
        public virtual tSubmenu tSubmenu { get; set; }
    }
}
