//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teatsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubmenu
    {
        public tSubmenu()
        {
            this.tNews = new HashSet<tNew>();
        }
    
        public int sub_id { get; set; }
        public Nullable<int> menus_id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string images { get; set; }
        public Nullable<System.DateTime> addedtime { get; set; }
    
        public virtual tMenu tMenu { get; set; }
        public virtual ICollection<tNew> tNews { get; set; }
    }
}
